name: CI Workflow

on:
  pull_request:
    branches:
      - 'master'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Add .env file
        run: cp backend/.env.template backend/.env

      - name: Generate static files
        run: python backend/manage.py collectstatic

      - name: Save node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: frontend/node_modules

      - name: Save venv
        uses: actions/upload-artifact@v4
        with:
          name: venv
          path: .venv

  frontend-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: frontend/node_modules

      - name: Run frontend test
        run: npm test -- --watchAll=false
        working-directory: frontend